global:
   scrape_interval: 4s
   evaluation_interval: 4s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']


  - job_name: 'ecs_cluster'
    static_configs:
      - targets: ['ecs-exporter:9222', 'node-exporter:9100']
